spring.application.name=absensi-app

# Database config
spring.datasource.url=jdbc:postgresql://localhost:5432/absensi_db
spring.datasource.username=postgres
spring.datasource.password=GANTI_INI
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8080